DROP DATABASE IF EXISTS dbSSIIMITH;
CREATE DATABASE IF NOT EXISTS dbSSIIMITH;
CREATE TABLE dbSSIIMITH.CLIENTE(
	username VARCHAR(20) PRIMARY KEY,
	password VARCHAR (20)
);
CREATE TABLE dbSSIIMITH.NONCE(
	nonce VARCHAR(20) PRIMARY KEY ,
	cs int
);
CREATE TABLE dbSSIIMITH.LOG(
	transaccion VARCHAR(20),
	success int,
	integrity_fail int,
	replay_detect int
);

INSERT INTO dbSSIIMITH.CLIENTE VALUES ("antrodote","SSII");